### ISSUE TITLE
UseItem currently throws a NullReferenceException

### ISSUE THREAD

**Issue by zzi-zzi-zzi** [BosslandGmbH/SenseibuddyBugs#2]
```
2016-07-17 16:44:50,611 [Pulsator Thread] INFO  UseItemTag - Equipping item Training Sword
2016-07-17 16:44:51,109 [Pulsator Thread] ERROR Profile Bot - Exception during execution of profile tag <UseItem Display="Equip Pre-Hongmoon Weapon" Items="610100,610101,610102,610103,610104,610105" SkipMissing="true" Equip="true" SleepTime="250" RefTag="PreHongmoonWeapon" /> (Line #74)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Buddy.BotCommon.CommonBehaviors.-o6xf\*\,=e-4A"q|M(jE3rS :\..MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Buddy.BotCommon.ProfileTags.UseItemTag.b9kP|C5NZeyM'H@{3 $F7sjq.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Buddy.ProfileBot.ProfileBot.5b@v":\,jFjroK\&pbRkwC\.WHj!.MoveNext()
```

**Comment by ApocDev** [comment]
UPDATE: Exception fixed. But "right clicking" is failing. Will need a separate issue.

**Comment by zzi-zzi-zzi** [comment]
Re-opened so I know it needs to be tested :)

**Comment by zzi-zzi-zzi** [comment]
Works well ;)
